server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_college
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  vod:
    file:
      keyid: 阿里云key
      keysecret: 阿里云秘钥
